<a href="https://colab.research.google.com/github/YASHYOGESHAHIRE/-Srch-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np

In [ ]:
lst = [1,2,3,4,5] # You can only store 1d array in python list
print(lst)

[1, 2, 3, 4, 5]


Advantage of Numpy Array over Lists

In [ ]:
print('1D Array')
a = np.array([1,2,3,4,5])
print(a)

print('2D Array')
b = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(b)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print('3D Array')
c = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print(c)

3D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
type(a)

numpy.ndarray

size = Tells about no. of elements in that array

In [ ]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


shape = (rows,cols)

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(3, 5)


dtype = Type of Data Present in the array

In [ ]:
print(a.dtype)

int64


In [ ]:
d=np.array([[1,2,3,4.2,5],
           [6,7,8,9,10],
           [11,12,13,14,15]])
print(d.dtype)

float64


arr.transpose()

In [ ]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8. , 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

np.empty((rows,cols),dtype)

In [ ]:
np.empty((4,4),dtype = int) #randomly generated int data

array([[   303190377,            0, 489626271861, 433791696995],
       [498216206368, 468151435365, 476741369968, 416611827826],
       [450971566194, 519691042924, 502511173664, 416611827822],
       [416611827830, 463856468073, 420906795105, 433791697004]])

np.ones((rows,cols),dtype)

In [ ]:
x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [ ]:
y= np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
z = np.ones((3,5),dtype=int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.zeros((rows,cols),dtype)

In [ ]:
x= np.zeros(4)
x

array([0., 0., 0., 0.])

In [ ]:
y=np.zeros((4,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
z=np.ones((4,8),dtype=str)
z

array([['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

In [ ]:
z=np.ones((4,8),dtype=bool)
z

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
z=np.zeros((4,8),dtype=bool)
z

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

np.arange(start,end,step)

In [ ]:
a=np.arange(1,20)  # One r only keep in mind
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


arr.reshape((rows,cols))

In [ ]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
b=np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
b=b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
b=b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
a=a.ravel()
a     # Same as flattn , but it is just an reference , it is faster than flatten as it does not occupy any memory
#if you modify the original array will also notice

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a= np.arange(1,51)
a= a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
a[0]

array([1, 2, 3, 4, 5])

In [ ]:
a[2]


array([11, 12, 13, 14, 15])

In [ ]:
a[0,0]

np.int64(1)

In [ ]:
a[3,4]

np.int64(20)

In [ ]:
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
a[0:10] # 0-9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
a[:,2] # Step Not, it is location again

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [ ]:
a[2:5,4]

array([15, 20, 25])

In [ ]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
a[:,2:5] # columns

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [ ]:
a[:,2:5].dtype

dtype('int64')